name: sifoodm
description: Um projeto de Food.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

## Slidy Scripts
vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner
scripts:
  mobx_build: $runner build
  mobx_watch: $clean & $get & $runner watch
  mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter_slidable: ^0.5.7
  overlay_support: ^1.0.5
  imei_plugin: ^1.2.0
  dashed_container: ^1.0.1
  configurable_expansion_tile: ^1.0.0
  floating_action_bubble: ^1.1.2
  wifi_ip: ^0.0.1
  udp: ^3.0.3
  animate_do: ^1.7.3
  easy_udp: ^1.2.0
  flutter_svg: ^0.19.1
  shared_preferences: ^0.5.12+4
  dio: ^3.0.10
  flutter_mobx: ^1.1.0+2
  mobx: ^1.2.1+4
  flutter_modular: ^2.0.1
  flutter_badged: ^1.0.2
  flutter:
    sdk: flutter
  flutter_screenutil: ^3.2.0

dev_dependencies:
  flutter_launcher_icons: '^0.8.0'
  effective_dart: ^1.2.3
  mockito: ^4.1.1
  modular_codegen: ^2.0.0+1
  mobx_codegen: ^1.1.0+1
  build_runner: ^1.10.1
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path: 'assets/images/logo/logo.png'

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo/
    - assets/images/decoration/
    - assets/images/icons/
    - assets/images/home/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-Regular.ttf
        - asset: assets/fonts/nunito/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/nunito/Nunito-Bold.ttf
          weight: 700
    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/raleway/Raleway-Regular.ttf
        - asset: assets/fonts/raleway/Raleway-Light.ttf
          weight: 300
        - asset: assets/fonts/raleway/Raleway-SemiBold.ttf
          weight: 600
    - family: CenturyGothic
      fonts:
        - asset: assets/fonts/century-gothic/century-gothic.ttf
